### ISSUE TITLE
Web interface seems to not work properly?

### ISSUE THREAD

**Issue by garret** [J-Siu/docker_amule#1]
Hey can you confirm that the web interface seems to be partially broken? For instance, I cannot see to which server I am connected to in the bottom part. Additionally, I cannot get KAD to work (I have put nodes.dat files and was managing with amule 2.3.2). Finally, the server log is always empty. 

Maybe all these errors are due to the use of a svn version?

**Comment by J-Siu** [comment]
Sorry for the supre late reply. Have you solve the issue yet?

Regarding KAD not working, and missing servers, that seems to be empty config. Have you map the volum correctly in the .env file or inside dockerfile?

**Comment by garret** [comment]
Actually not. The issue is that I also built an image of docker from scratch (https://github.com/garret/amule-raspberrypi, alpine base) and when using the latest svn verion I get the same issues. I am very confident that the variables are correctly filled and the config file is loaded. 

Everything works fine when using the latest stable version of amule (v2.3.2) instead. 

Recapping, I have problem in the KAD page (doesn't seem to connect to the nodes), in the config page (have blank field for config settings despite I can see that settings are correctly loaded from the amule.conf) and in the log page only the bottom pane shows a log while the on top stays blank. 

May I kindly ask you a screenshot from your web interface taken on the KAD, config and log page (of course obfuscating sensible fields)?

**Comment by J-Siu** [comment]
SVN shouldn't be the issue as alpine always use that branch. I just tested it and it is working on my end.

![KAD](https://i.ibb.co/8md2Khv/Screen-Shot-2021-01-15-at-9-33-28-AM.png)

In your amule.conf, check if following match your firewall setup:

- Port=
- UDPPort=

Additionally, the uid and gid of ${AMULE_DIR} should be used for ${AMULE_UID} and ${AMULE_GID} in the .env file.

**Comment by garret** [comment]
I am pretty sure about my ports because if I use an image with stable amule I can connect to Kad and server with high ID and I am not firewalled. In any case, may I ask you how do you see the settings page? 

This how I see it. Essentially, you don't see the real settings and all the fields are empty. I am curious if you experience the same issue. 
![image](https://user-images.githubusercontent.com/27555/104851768-44d66600-58f7-11eb-8cc4-952b5143f2b9.png)

**Comment by J-Siu** [comment]
Mine show correctly. Have you set a password for the web interface yet? I kind of remember without password, the web gui is not fully functional.

![](https://i.ibb.co/ZNRFCjW/Screen-Shot-2021-01-17-at-5-34-12-PM.png)

**Comment by garret** [comment]
Yes, I am using a password to access the web gui. I tried the container on a raspberry pi and on a x86_64 pc and I have the same issue. In any case, I can live with that as I can see that the correct settings in my amule.conf are loaded. Thank you anyways! :)
